---
###########################################################################
# User variables                                                          #
###########################################################################

# Defaults to latest stable, change if you want a specific Kubernetes version
# kubernetes_version: stable-1

# Change this to an IP range reserved on your network
# metallb_ip_range: '192.168.17.100-192.168.17.200'

# Make sure these numbers are <= the number of disks available in your cluster
# storage_data_replicas: 3
# storage_metadata_replicas: 3

# Change this to the subdomain you're using for your cluster services
# cluster_subdomain: example.org

# At least one of these must be enabled and set to default or the playbooks
#   will fail, as they assume that PVs can be dynamically provisioned.
# Set to true to create CephBlockStorage
# storage_block_create: false
# Set to true to make block storage the default storageclass
# storage_block_default: false
# Set to true to make a CephFilesystem
# storage_cephfs_create: true
# Set to true to make cephfs the default storageclass
# storage_cephfs_default: true

# Change these to configure cluster backup to NFS. If you don't set these no backup
#   solution will be deployed.
# nfs_backup_share_path: /export/backup
# nfs_backup_server: nfs.example.org

helm_version: v3.2.1

# Alter schedule for backup using cron syntax. Default is once per day.
velero_backup_schedule: '0 7 * * *'

# How long to save backups, in hours. Defaults to two weeks.
velero_backup_ttl: 336

# Set these to false to skip deployment
# deploy_murmur: false

###########################################################################
# Project variables                                                       #
# -----------------                                                       #
# These should work as-is, modification is still possible but it will be  #
# very easy to break things                                               #
###########################################################################

# Will only make the master schedulable in a single-node cluster
master_node_schedulable: '{{ (groups.nodes | length) == 1 }}'

artifacts_dir: "{{ (playbook_dir + '/../artifacts') | realpath }}"

backup_nfs_pv:
  apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: backup
  spec:
    accessModes:
    - ReadWriteMany
    capacity:
      # just a big number, doesn't actually matter
      storage: 100Ti
    nfs:
      path: '{{ nfs_backup_share_path }}'
      server: '{{ nfs_backup_server }}'
    persistentVolumeReclaimPolicy: Recycle
    storageClassName: nfs
