galaxy_info:
  author: Fabian von Feilitzsch
  description: Configures the ingress-nginx ingress controller along with metallb for Kubernetes
  license: AGPL-3.0-or-later
  min_ansible_version: 2.9
  platforms:
    - name: Centos
      versions:
      - 7

  galaxy_tags:
    - kubernetes
    - homelab

# dependencies:
#   - community.kubernetes
