galaxy_info:
  author: Fabian von Feilitzsch
  description: Configures the Homer dashboard in Kubernetes
  license: AGPL-3.0-or-later
  min_ansible_version: 2.9
  platforms:
    - name: Centos
      versions:
      - 7

  galaxy_tags:
    - kubernetes
    - homelab

# dependencies:
#   - community.kubernetes
