---

- name: ensure required sub-projects exist
  hosts: localhost
  connection: local
  tasks:
    - name: clone projects
      git:
        repo: 'https://github.com/openshift/openshift-ansible.git'
        dest: /tmp/openshift-ansible
      when: clone_projects | default(True)

- name: If no masters exist, fail out
  hosts: localhost
  connection: local
  tasks:
    - fail: msg="No master registered to foreman"
      when: groups['masters'] | length == 0


- include: /tmp/openshift-ansible/playbooks/byo/config.yml
  when: install_openshift|default(True)

- hosts: oo_first_master
  gather_facts: false
  tasks:
    - name: Grant cluster-admin permissions to admin user
      command: oc adm policy add-cluster-role-to-user cluster-admin admin

- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: oc login
      command: oc login -u admin -p admin
